apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alexellis-store-gist
  namespace: openfaas-fn
spec:
  encryptedData:
    github-token: AgCcAFQDkj4A94l2pcRY3WTp3cMARz73Rg3cXemuma3eFEGHr/6MzYDdiMYh1KVqNrHLo0SxNNhMjzi7cV3XmXHvkbau4sST0qoJwVaXmxg4LB5tNZG+iy14Yi4IKS8GqCrbzsuK0P1yNsh87ccrh3MmAPF8Mj3O5pj3UGA5eXytfhSeuKfwlRBxoRwM2IbKmTA2l+Axr2BPfbufoC1lG4KbvFnmef5AyL8i3D/2PWv39PlmBDPSuzddtxjlwYdrHnfHJnoiVZTkSBb6+dYHgZ7RT+utjBjiQj8W10RoQimV2P/04YMmbSyi+jpaaCYG3nk2Ab9TxJRNkrlNnB4gSK4D01qfHXNipfzgkWzcDwGCFD/yI25XSJgj0r6brUi8i0zGQpRZ6fgUAf0WlZHVbe1aSYQvfJ3JcuDkUHFpHQ3dKHRlOBuTNDogSUy59dKkCfgR1iZXoXEj0J2kRbfVhHIMFd2kqzxKQuqnbQHjk8Xz9dKwM/vLFuk+vv2XGEQta1pNSxp2zfosiPfVxaF8/a19RhCWy9j3vVnGjPFLw53YfTJGYYUehGkSHVeMj95aXHMFxOJhOFIWFV/FwWn4KKflFfsKUOiJ2X3Mw97CZIml0I0D0NSbf0VNGgeOIKwR28xn5zr67wjEzGewdHE5mxIq8ZyP1Ce9MFm81NEpFpQ4wyC/RUKRMsMHK33cHEDZtA1LlW6tNVLwqI4SSB5ujpK/Bw/2G0i0k0P/Rdu/Ms1Lc6AnysbHwrme

